### ISSUE TITLE
Color code errors and warnings in IDE

### ISSUE THREAD

**Issue by jpreese** [jwldnr/VisualLinter#10]
### Installed product versions
- Visual Studio: 2017 Professional
- This extension: 1.0.120

### Description
When linting, the color used in the IDE is always green. Regardless if the linting issue is an error or a warning. The Output window does show this distinction.

### Steps to recreate
1. Add a linting rule as a warning and a linting rule as an error
2. Violate these rules within code

### Current behavior
The IDE will display both linting issues as a green line.

### Expected behavior
The error should be a red line, where as the warning should be another.

**Comment by jwldnr** [comment]
Thank you for your report @jpreese!

This has already been addressed for the error list (as you mention) in pull request #2 (courtesy of @philwsac).
I've gone ahead and added the same distinction in the buffer depending on rule severity.
You can view the changes in this commit: 99340c79acdeb643ec746c4b9d0a81f9d74e96da
