### ISSUE TITLE
Visual Studio does not display any errors

### ISSUE THREAD

**Issue by andre-f-paggi** [jwldnr/VisualLinter#14]
### Installed product versions
- Visual Studio: 2017 Enterprise
- This extension: 1.0.158

### Description
I just installed this extension, but I couldn't make it work yet. There are no messages being displayed in the Error List.

### What I've done and tried
The Eslint executable is in the PATH global variable and the eslint configuration file is valid, since I tested it on the command line using it.
I disabled ESLint and the language service in the Option > Tools > Text Editor > Javascript.
Tried enabling one and disabling the other one, but none of this worked.

There is no error message when I start Visual Studio or whatever.

I want so bad to use this extension! 🙂

**Comment by andre-f-paggi** [comment]
I am sorry, found the error in the Output window.

The problem was that I didn't installed eslint locally, I thought that installing it globally would work

My bad!

**Comment by jwldnr** [comment]
installing ESLint globally still works if you tick the checkbox 'Use personal ESLint config instead of local' under Tools > Options > VisualLinter.
