### ISSUE TITLE
VisualLinter keeps getting disabled by Visual Studio 2017

### ISSUE THREAD

**Issue by magkal** [jwldnr/VisualLinter#21]
### Installed product versions
- Visual Studio: 2017 Profressional (running as administrator)
- This extension: 1.0.198
- Windows 10 x64

### Description
VisualStudio keeps disabling the extension for me, If i enable VisualStudio linter and restart Visual Studio, it mostly is active.
After working a while with .js-files, the next day i start visual studio VisualLinter is disabled. 
Yesterday i got a warning of that some typescript-file had caused errors and would be disabled, so i had a thought there could be some underlying exceptions with this extension or it being in conflict with another extension/function in visual studio.
Sorry this is quite vague, but maybe someone has experienced this?

### Steps to recreate
1. Enable VisualLinter
2. .eslintrc.js and .eslintignore Exists in my root folder
3. Work some in javascript files, save and trigger linting.
4. Shut down Visual Studio
5. Open Visual Studio again, go to Tools > Extensions and updates.. > Installed > VisualLinter is now disabled

### Current behavior
VisualLinter should be enabled but is not

### Expected behavior
VisualLinter should be enabled until i choose to disable it

**Comment by jwldnr** [comment]
@magkal This problem could be caused by having multiple versions of the same extension installed. Before I investigate further, could you ensure that you only have one version of the extension installed?

**Comment by magkal** [comment]
I don't have it installed for multiple versions of Visual Studio if that's what you mean. Just for Visual Studio 2017, however I've upgraded the extension a couple of times.
Did some googling and couldn't find anything pointing me in a direction how to see if the extension is installed in more than one version in the same version of Visual Studio.

**Comment by jwldnr** [comment]
@magkal in Visual Studio under `Tools > Extensions and Updates...` in the list `Installed`, are there multiple entries of `Visual Linter`? 
Tip: you can filter extension in the list by using `Search (Ctrl+E)` in the top right.

**Comment by magkal** [comment]
There is just one entry of VisualLinter there.

**Comment by jwldnr** [comment]
@magkal have you tried reinstalling the extension through `Tools > Extensions and Updates...`? I'm hoping this is just a random occurrence.
