### ISSUE TITLE
VisualLinter doesn't run on all file in the directory, like .vue files.

### ISSUE THREAD

**Issue by paparent** [jwldnr/VisualLinter#23]
### Installed product versions
- Visual Studio: 2017 Community 15.4.0
- This extension: 1.0

### Description
VisualLinter doesn't run on .vue files. Here's my .eslintrc file as an example:

```
module.exports = {
  extends: [
    'airbnb-base',
    'plugin:vue/recommended',
  ],
  parserOptions: {
    parser: 'babel-eslint',
  },
  env: {
    browser: true,
  },
  rules: {
    'linebreak-style': 0,
    'unicode-bom': 0,
  },
};
```

### Steps to recreate
1. Add .vue file to the project
2. Configure eslint as the example above to support .vue files
3. Run Linter

### Current behavior
It doesn't run, but in command line, if I run with `eslint src/**/*`, in order to assure it runs on all file and not only .js file, it show errors.

### Expected behavior
Should be able to run on the whole file since the eslint-plugin-vue support all the section. For example, in the HTML if I don't put a `key` with `v-for` directive, I get that error:

`13:7  error  Elements in iteration expect to have 'v-bind:key' directives  vue/require-v-for-key`

**Comment by jwldnr** [comment]
Could you provide a sample `.vue` file for testing?

**Comment by paparent** [comment]
```
<template>
      <div v-for="x in 10">{{ x }}</div>
</template>
```
