### ISSUE TITLE
Show parsing-errors in error-list

### ISSUE THREAD

**Issue by Epaminaidos** [jwldnr/VisualLinter#26]
### Installed product versions
- Visual Studio: 2017 professional
- This extension: just installed

### Description
Parsing errors are only shown in the output-window.

### Steps to recreate
Create a js-file with only a single line: 1==0?;

### Current behavior
The error-list in VS is empty, the error is only shown in the output-window.

### Expected behavior
I think it would be more intuitive to see the parsing-error in the error-list. The code will not execute after all. Why let the developer execute the code if VisualLinter does already know it won't run?

**Comment by jwldnr** [comment]
Hi @Epaminaidos Thank you for your suggestion!
I agree that it would indeed be more intuitive to show this error in the error list instead of the output window. 
I'll update back here once I've gotten around fixing it!

**Comment by jwldnr** [comment]
I've reverted the changes made to catch the parser error message in version `1.0.223`, I honestly don't remember why I did this in the first place, but I'm sure we'll find out soon enough. (in before revert revert)

The new version will soon be available on the Market place.
