### ISSUE TITLE
feature: Run command after successful (no errors) lint

### ISSUE THREAD

**Issue by ChristineBoersen** [jwldnr/VisualLinter#29]
Feature Request:
It would be nice to have the ability to run a command and output it's output to the output window on a successful lint.

**Comment by jwldnr** [comment]
Hi @ChristineBoersen thank you for the feedback!

If I understand you correctly, you would like VisualLinter to output text similar to "linting done with no errors" in the output window?

**Comment by jwldnr** [comment]
Since it's been a week without feedback I'm going to close this issue.
Comment here with additional information If you want me to reopen the issue!
