### ISSUE TITLE
Inability to Target Project's .eslint File

### ISSUE THREAD

**Issue by benrondeau** [jwldnr/VisualLinter#3]
### Installed product versions
- Visual Studio: 2017 Professional, v15.2
- This extension: 1.0.89

### Description
As [documented](https://github.com/jwldnr/VisualLinter#getting-started) in the Getting Started section of the README, this extension targets the `.eslintrc` file in the user's root directory I can't find a place to configure the plugin to look for my project's `.eslintrc` file, so I have to manually change the file in my root directory when I change projects.

Different projects have different configuration files (ES5 project, ES6 projects, React projects, etc.) but this plugin only allows you to target the one global file. This is very inconvenient and an antipattern compared to other IDE's (like Webstorm) which allow you to target the `.eslintrc` file you want to use. This is a MUST for projects that have different settings.

This also may NOT be an issue with the plugin, but instead a restriction of Visual Studio.

### Steps to recreate
1. Open Visual Studio
2. Open Project
3. Select Menu Item `Tools > Web Code Analysis > Edit Eslint Settings`
4. See that the file VS is targeting is at the root of user's directory, not in the project's directory

### Current behavior
It targets the `.eslintrc` file in the user's root directory (ie. `C:/Users/Name/.eslintrc`) with no ability to change the target (that I am aware of)

### Expected behavior
I expect it give me the choice to target the `.eslintrc` file of my choice, in this case the project's file

**Comment by philwsac** [comment]
Hi @benrondeau. I think this extension does what you want: If you put a .eslintrc file at the root of your project (or in a folder of your project), ESLint (via this extension) will pick it up and use it. 

I could be mistaken, but my understanding is this extension operates outside of the Visual Studio / Web Code Analysis configuration. For my personal use, I turned off the Visual Studio 2017 ESLint stuff (via Tools > Options > Text Editor > JavaScript/TypeScript > EsLint > Enable ESLint > False).

This extension is essentially a wrapper around running eslint from the command line, so it follows the ESLint rules for finding config files. Does this help resolve your situation?

**Comment by benrondeau** [comment]
Unfortunately I cannot get this plugin to pickup the `.eslintrc` file in my project. If I can do that, my problems are solved.

How can I do that?

**Comment by philwsac** [comment]
The extension is a little picky, as it is very new, so it's easy for it to not work. My understanding is this:
 * An .eslintrc file is needed in your Windows user home folder. The extension will not work if nothing is there.
 * You need to have all the ESLint plugins that are listed in your ESLint config files. For example, if your root config has react stuff in it, it's possible ESLint is throwing an error because it can't find the react plugin. (This happened to me. Also, in my experience it fails silently, so it's hard to tell if it's broken.)
 * I think the linter only runs when you open files / save them. I'm still not entirely sure how this works, but my point is that rule changes in your config files can take a few seconds / some time for the linter to pick up.

**Comment by jwldnr** [comment]
As @philwsac pointed out the extension should target an `.eslint` file in the current project directory before the user root directory. However I discovered this by coincidence and I will update the extension once I get back from my vacation with an option to target an `.eslint` file in the current project directory explicitly.

Sorry for not getting back to you earlier but I'll get on this when back from my vacation.

**Comment by benrondeau** [comment]
Thanks so much!

**Comment by jwldnr** [comment]
I have addressed the issue in the following pull request (merged into master): https://github.com/jwldnr/VisualLinter/pull/4

The default behavior of the extension is now changed from using a global config to using a local config (relative to the file being linted).

I have also provided an options page with a checkbox to toggle the previous behavior (using a global config). You can find the new options under `Tools > Options >  VisualLinter`. 

Please note that the menu item `Tools > Web Code Analysis > Edit Eslint Settings` will never show the `.eslintrc` file being used by this extension. This is a default config file provided for the built in ESLint (integrated with Visual Studio 2017)

There will soon be a new version of the extension available on the Marketplace. Please upgrade the extension to version **1.0.106 or higher** to ensure the availability of these new features.

I will go ahead and close this issue. However, feel free to post back here (or submit a new issue) if anything isn't working as you'd like- and I'll reopen this issue.

**Comment by benrondeau** [comment]
Thanks so much!
