### ISSUE TITLE
"Unexpected character encountered" in local ESLint installation but ok in global

### ISSUE THREAD

**Issue by Kiruchi** [jwldnr/VisualLinter#34]
### Installed product versions
- Visual Studio: 2017 Enterprise
- This extension: 1.1.27

### Description
First, thanks a lot for the extension, I've been trying for a long time to have a decent ESLint integration in VS2017.

I am having an error when launching this extension with a local installation of ESLint (you can see on the top left ESLint is locally installed) : 

![2018-01-26 10_52_18-microsoft visual studio](https://user-images.githubusercontent.com/3627263/35434523-c8de2a92-0287-11e8-801b-1a776c72f284.png)

When I duplicate my local package.json in my global package.json and check the option to use the globally installed version, it works.
It seems to happen only on local installation of ESLint (but as we can see in the screenshot ESLint is installed (in devDependencies)

Extract of my local package.json :
![image](https://user-images.githubusercontent.com/3627263/35434637-28a84926-0288-11e8-9186-82b9fd7ba2ce.png)

### Steps to recreate
1. Install ESLint locally on the project (I have a solution with 2 projects, maybe I have to install it on the backend project as well ?)
2. Install the extension

### Current behavior
Not working in local ESLint installation but ok in global.

### Expected behavior
Working as expected.

**Comment by jwldnr** [comment]
Hey @Kiruchi ! Thanks for your report.

The first thing I notice is that the recursive folder traversing when finding `eslint` installation in `node_modules`, in your case is matching, and is using `gulp-eslint` instead of actual `eslint` installation (which should not happen).

It is possible that the version used is not compatible with your configuration (???).
Could you please be so kind as to post back here with the contents of your `.eslintrc` for me to test against?

Cheers!

**Comment by jwldnr** [comment]
I've published a new version `v1.1.34` to the Marketplace which alters the way that the ESLint executable path is resolved inside the `node_modules` directory. It should be available in just a moment. 

Please update the extension through Visual Studio and use the new version for further testing.

**Comment by Kiruchi** [comment]
I updated my local ESLint to 4.16.0 and VisualLinter to 1.1.41 and it is now working as expected.

Thank you for your time and for this extension.
Cheers.

**Comment by jwldnr** [comment]
Awesome @Kiruchi ! Thanks for letting me know 😄
