### ISSUE TITLE
Incompatibility with Extension Vue.js Pack 2017

### ISSUE THREAD

**Issue by zcharleshebert** [jwldnr/VisualLinter#41]
### Installed product versions
- Visual Studio: Visual Studio 2017 Enterprise
- This extension: 1.1.59
- Vue.js Pack 2017
### Description
The title summarize it, I believe. 

### Steps to recreate
1. Have a already working Vuejs project with linting (via VisualLinter) works
2. Install latest version of Vue.js Pack 2017 extension 
3. Open any .vue files
4. Eslint not working for .vue files, but still work for .js files

### Current behavior
VisualLinter doesn't lint .vue files anymore

### Expected behavior
VisualLinter should lint supported files even with other extensions installed (imo)

### Notes ;p
It seems that Vue.js Pack 2017 adds intellisense/goodies to the .vue file in a way that changes the ContentType of Vue Files that you open.

I could make it work by adding
`[ContentType("projection")]` to the TaggerProvidder class
-> [Here](https://github.com/jwldnr/VisualLinter/blob/a2ea7ab4ed352e204ea0dc4db84127aea0cb6405/src/VisualLinter/Tagging/TaggerProvider.cs#L25)

...but I was wondering if that was the right way of doing this ?

Please let me know ASAP, since it would be game changing for our team...

So I'll make the PR for you. :)

Cheers,
C

**Comment by jwldnr** [comment]
Hey @zcharleshebert !

Its absolutely fine to add the `[ContentType("projection")]` in the TaggerProvider class.
Send me a pull request and I'll make it happen!

For reference:
https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/inside-the-editor.md#projection

**Comment by jwldnr** [comment]
closed in #42

Thanks for the help @zcharleshebert !

**Comment by jwldnr** [comment]
Feature added in `v1.1.60`.

**Comment by zcharleshebert** [comment]
My pleasure @jwldnr !
