### ISSUE TITLE
Add ability to recognize files that extend the base .eslintrc rules

### ISSUE THREAD

**Issue by Blackbaud-ThomasOrtiz** [jwldnr/VisualLinter#43]
### Installed product versions
- Visual Studio: 2017 profession
- This extension: 1.1.60

### Description
My team has the following files:

* `.eslintrc` - base rules
* `dev.eslintrc` - dev only rules that extend base rules found in `.eslintrc`
* `prod.eslintrc` - prod only rules that extend base rules found in `.eslintrc`

Currently, the extension only pulls the rules from `.eslintrc` meaning that it does not use our `dev.eslintrc` rules that override those base rules found in `.eslintrc`. 

### Current behavior
The extensions pulls solely from the `.eslintrc` file. Any rules in dev/prod versions of the file do not work with this extension.

### Expected behavior
The extension should pull from the `.eslintrc` file and allow me to add extra files that extend/overwrite the rules in the base `.eslintrc` file. All rules (including those that get overwritten from the extension files) should work with the error list.

**Comment by jwldnr** [comment]
Thanks for the feature request @blackbaud!

I’ll have a look at this. It has been on my todo list for a while now since it’s the default behavior of eslint.

I’ll keep this issue open until I’ve reached a conclusion.

**Comment by jwldnr** [comment]
Added in version `1.1.63`.
