### ISSUE TITLE
VS Crashes On JS File Save After Update To 15.7

### ISSUE THREAD

**Issue by jwbats** [jwldnr/VisualLinter#46]
### Installed product versions
- Visual Studio: 15.7 Community
- This extension: 1.1.63

### Description
Visual Studio updated. Now JavaScript file saves make VS crash.

Upon reopening the project, the file has been correctly saved. But you can't work with a crash for every JS save you do.

### Steps to recreate
1. Use the above VS version with the above VL version.

### Current behavior
VS crashes on JS file save.

### Expected behavior
VS does not crash on JS file save.

**Comment by jwldnr** [comment]
Thanks for the report, but this issue has already been reported. I’m going to close this in favor of #45.
Discussion will continue there. 👍
