### ISSUE TITLE
Publish new version with fix for Newtonsoft.Json not found

### ISSUE THREAD

**Issue by madskristensen** [jwldnr/VisualLinter#47]
You don't actually have to include newtonsoft.json.dll in the .vsix. It is considered a bad practice to do so. You just have to use a lower version to make the binding redirects work in VS2017. Downgrade JSON.NET to version 8 and don't include it in the VSIX and it should work fine.

But regardless of downgrading or including the latest version, can you please update the extension on the Marketplace with the fix?

**Comment by madskristensen** [comment]
Don't do binding redirects. Visual STudio ships with those for JSON.NET. It's better to downgrade to version 8 to make sure it works with un-updated versions of VS2017. VS will automatically update it using binding redirects to version 9

**Comment by jwldnr** [comment]
Alright @madskristensen, fair point.
Any specific version 8 or will any do?

**Comment by madskristensen** [comment]
8.0.3 will do. Generally speaking, when using JSON.NET in a VS extension always use the lowest possible version you can. So if you can use version 6 in your extension then do that instead.

**Comment by jwldnr** [comment]
Thanks @madskristensen, I must admit it has given me some headaches. I'll downgrade to `v8.0.3` and release it to the marketplace, but I'll be sure to research earlier versions as well.

**Comment by madskristensen** [comment]
awesome

**Comment by jwldnr** [comment]
fixed in #48 
a new version will soon be available on the Marketplace. Thanks @madskristensen!
