### ISSUE TITLE
Parsing Error

### ISSUE THREAD

**Issue by benrondeau** [jwldnr/VisualLinter#5]
### Installed product versions
- Visual Studio: 2017 Professional
- This extension: 1.0.108

### Description
Getting this error in the output window for VisualLinter:

`Unexpected character encountered while parsing value: C. Path '', line 0, position 0.`

This is my `.eslintrc` file contents:

```json
{
  "extends": "airbnb-base",
  "rules": {
    "linebreak-style": "off",
    "indent": "off"
  }
}
```

### Steps to recreate
1. Open Visual Studio
2. Open a JavaScript file
3. Open output window and select VisualLinter in drop down menu

### Current behavior
No linting, providing above error message

### Expected behavior
Provide linting without errors

**Comment by jwldnr** [comment]
You're seeing this message because there was a problem with your `.eslintrc`, for example a module required by the config is missing.

I have updated the code in version **1.0.111** to log the output of ESLint which could help you identify the problem.

**Comment by benrondeau** [comment]
Thanks!

**Comment by jwldnr** [comment]
Did the new logging entry help you find what was missing? @benrondeau

**Comment by benrondeau** [comment]
I am now getting eslint error output and working on debugging from that.

**Comment by jwldnr** [comment]
OK. I'll consider this issue solved then! Feel free to open a new issue if you still have problem with the extension!
