### ISSUE TITLE
[babel-eslint/v11] Specified argument was out of the range of valid values. Parameter name: lineNumber

### ISSUE THREAD

**Issue by icoumans** [jwldnr/VisualLinter#53]
### Installed product versions
- Visual Studio: 2017 Professional
- This extension: 1.1.89 (problem also existed with 1.1.88)

### Description
When running the extension, the following error is shown in the Output Window:
Specified argument was out of the range of valid values.
Parameter name: lineNumber

### Steps to recreate
1. Install the extension
2. Run Visual Studio
3. Open the Output Window

### Current behavior
Instead of running the linter, only the error is shown in the Output Window.

### Expected behavior
It should run the linter.

**Comment by jwldnr** [comment]
Hi @icoumans could you create a reproducable

**Comment by icoumans** [comment]
> Hi @icoumans could you create a repo for me to test against? The exception you're getting is tightly coupled with the contents of the file being linted. It would help with debugging.
> 
> Thank you

I really should have thought about my recent changes before posting this issue. I've been upgrading some packages to use the latest experimental proposals. It looks like the 'culprit' is babel-eslint 11.0.0-beta.0. I don't know whether this issue belongs to VisualLinter or babel-eslint.

When I disable the plugin, or downgrade the version, the issue no longer appears.

I have attached a simple test project which demonstrates the issue (note that I have not included any babel config - the issue appears regardless).

[TestRepo.zip](https://github.com/jwldnr/VisualLinter/files/2821500/TestRepo.zip)

**Comment by icoumans** [comment]
> When you say disable the plugin, or downgrade the version do you mean babel-eslint?
Yes, babel-eslint.

**Comment by jwldnr** [comment]
> > When you say disable the plugin, or downgrade the version do you mean babel-eslint?
> 
> Yes, babel-eslint.

Ok, It might be that they've changed something (probably index starting values) in v11 of eslint. I'll have to check. 😸

**Comment by jwldnr** [comment]
OK, I am able to reproduce this and like you said, its a compatibility problem with `babel-eslint@^11`. This is something I will have to look further into, but unfortunately don't have the time currently.
I will keep this issue open.

As a workaround you can downgrade `babel-eslint` to version 10.

**Comment by woldner** [comment]
Sorry everyone; but the development of this extension has been suspended. 
You can read more about it here:
https://github.com/jwldnr/VisualLinter#deprecated
