### ISSUE TITLE
Add Support for TypeScript JSX files (TypeScript React) (.tsx)

### ISSUE THREAD

**Issue by mklosterboer** [jwldnr/VisualLinter#57]
### Installed product versions
- Visual Studio: 2019 Professional
- This extension: 1.1.100

### Description
Add support for TypeScript React files (.tsx)

### Steps to recreate
N/A

### Current behavior
Currently you can enable .jsx and .ts files, but TypeScript JSX files, i.e. TypeScript React files are not linted in Visual Studio.

### Expected behavior
This would require the correct plugins for eslint to work, but on your side should just be adding the file extension. At least it appears that way from #55 .

I'm happy to contribute to a fix if you would prefer that. Just let me know. 

Thanks!

**Comment by jwldnr** [comment]
Hey @mklosterboer
Sounds good to me. If you'd create a pull request for this change I'll be happy to review it! Let me know if I can help.

**Comment by mklosterboer** [comment]
Perfect. I'll work on that and get a PR started. Thanks for the quick response!

**Comment by mklosterboer** [comment]
@jwldnr 
This may be a silly question, but I'm having trouble building the solution to test it because of what looks like some custom tools. 

I am unable to test as a result of this, but I am pretty sure I'm done. 

How do you feel about either of these options:

1. Building my branch and giving me the VSIX file to test
1. Me submitting a PR and you do any testing you would have done as part of the code review process. 

This just seems to be a development environment issue and I don't know that I want to keep fighting it over a pretty simple code change. 

Any thoughts?

**Comment by mklosterboer** [comment]
@jwldnr 
Nevermind. I figured out the issue. I'm was able to test it and I'm going to open a PR now. It looks like it's working like charm.
