### ISSUE TITLE
Visual Studio 1017 - No Local Eslint Found

### ISSUE THREAD

**Issue by jpx2001** [jwldnr/VisualLinter#59]
### Installed product versions
- Visual Studio: 2017 Enterprise Version 15.9.12
- This extension: [1.1.104]

### Description
VisualLinter prints "exception: no local eslint found"

However, ESLint shows warnings and bugs in the Error window. I don't know if the Output window text is wrong or if this is a real problem.

### Steps to recreate
1. Build or rebuild an ASPNet MVC project that has javascript files.
2. Open the Output Window
3. Show output from: VisualLinter
4. VisualLinter prints "exception: no local eslint found"

### Current behavior
VisualLinter prints "exception: no local eslint found"

### Expected behavior
Should not display the above message. Because VisualLinter has always done this, I don't know what, if anything, VisualLinter should print to the Output window. It needs to work properly for me to know what to expect.
![Output Window](https://user-images.githubusercontent.com/52963452/61296015-e9299a80-a79e-11e9-9191-44fb1b043179.png)
![Error Window](https://user-images.githubusercontent.com/52963452/61296025-ec248b00-a79e-11e9-9fd6-7bbbe1fce7f8.png)
![About Visual Studio](https://user-images.githubusercontent.com/52963452/61296032-efb81200-a79e-11e9-83f2-fde9e004b6a5.png)
![Visual Studio Extensions and Updates](https://user-images.githubusercontent.com/52963452/61296038-f3e42f80-a79e-11e9-8574-94572a290e8b.png)

**Comment by jwldnr** [comment]
Hey @jpx2001!
Are you sure that you've installed eslint locally (e.g. exists in your `package.json`) and it is VisualLinter that are reporting the errors in the error list? 
You see, Visual Studio 2017, and newer, has built in ESLint support. The difference between VisualLinter and the built in functionality is that VisualLinter will always use the ESLint version you've installed in your project, while the built in is using a bundled (and often very old) version of ESLint.

See the [Troubleshooting](https://github.com/jwldnr/VisualLinter#known-issues) section of the readme, on how to disable the built in features and ensure it is VisualLinter that reports the errors.

**Comment by jpx2001** [comment]
Jean,

Thank you so much for your quick response.

I have eslint installed globally and a package.config file in the root of my repository source folder.

·         Do I need to install eslint locally to each web project?

·         Can I install locally to the solution folder?

Thanks

**Comment by jwldnr** [comment]
No problem!
The default behavior is set to use a local installation of ESLint (per project).

If you wish to use a global ESLint installation, you will need to enable this option in Visual Studio under `Tools` > `Options` > `VisualLinter`.

See the [notes](https://github.com/jwldnr/VisualLinter#notes) section of the readme on how to configure global installation and/or config settings. 😸

**Comment by pmcelhaney** [comment]
I'm on Visual Studio 2019 (16.1.3) and getting the same error.

I have ESlint installed locally. Running `./bin/eslint .` works fine. The built-in version is also running the locally installed ESLint.

**Comment by jwldnr** [comment]
Could you share the full path to the file you're trying to lint and also the full path to where eslint is installed (in node_modules)

Thanks

**Comment by pmcelhaney** [comment]
It’s something like z:\code\project\file.js

ESLint and the plugin are installed at z:\code\project\package.json

The problem is ESLint looks for plugins relative to the current working directory, which is the user directory when run from Visual Studio.

**Comment by Indigo744** [comment]
Same issue on VS 2019.

VisualLinter configured to use local install (and analyze only ts/tsx files).
ESLint is installed in the project.
Running eslint manually works fine.

![image](https://user-images.githubusercontent.com/7137528/66637441-540a3680-ec13-11e9-9200-926a1f048695.png)

![image](https://user-images.githubusercontent.com/7137528/66637473-62585280-ec13-11e9-9e3a-59c8a8f27f2c.png)

**Comment by woldner** [comment]
Sorry everyone; but the development of this extension has been suspended. 
You can read more about it here:
https://github.com/jwldnr/VisualLinter#deprecated
