### ISSUE TITLE
Feature Request - Prefer a local installation of ESLint over global

### ISSUE THREAD

**Issue by sgordon3** [jwldnr/VisualLinter#6]
### Installed product versions
- Visual Studio:  2017 Professional
- VisualLinter 1.0.116
- eslint 7.0.1

### Description
VisualLinter will find a local eslintrc file and use it for configuration but it still requires that ESLint and all of it's plugins are installed globally. If you want to use different versions of plugins for different project along with VisualLinter, you can't with this version. Is there a possible roadmap for making it possible to use a locally installed ESLint?

### Current behavior
fatal error due to eslint not being found if not installed globally. Installing globally causes errors for not found eslint plugins

### Expected behavior (Hoped for behavior)
VisualLinter is able to make use of a locally installed eslint (node_modules directory)

**Comment by jpreese** [comment]
Completely agree. I've opened a PR to get this implemented.

**Comment by jwldnr** [comment]
I've had this idea for a while, just never got around to implement it. I'm looking at @jpreese  pull request #7 and I'm thinking we'll have this available later today!

**Comment by jpreese** [comment]
That would be awesome, @jwldnr ! We're actively looking into eslint extensions for VS2017, since the default capabilities just don't seem to be there (eslintrc in user profile, no highlighting within the IDE). 

This gets us everything we need with the exception of this piece.

**Comment by jwldnr** [comment]
implemented in #7
