### ISSUE TITLE
Add the terms 'visual' and 'visual linter' to search tags on VS Marketplace

### ISSUE THREAD

**Issue by ImportTaste** [jwldnr/VisualLinter#60]
Currently, if you search for 'visual linter' instead of 'visuallinter', it doesn't show up at all in the first page of results. I believe this is because 'visual' and 'visual linter' are missing from the tags.

**Comment by jwldnr** [comment]
Hi @ImportTaste!
Thank you for the suggestion. We should definitely do this!
I'll get on it once I get some free time.

**Comment by woldner** [comment]
Sorry everyone; but the development of this extension has been suspended. 
You can read more about it here:
https://github.com/jwldnr/VisualLinter#deprecated
