### ISSUE TITLE
"The path is not of a legal form"

### ISSUE THREAD

**Issue by pmcelhaney** [jwldnr/VisualLinter#61]
### Installed product versions
- Visual Studio: Professional 2017
- This extension: 1.1.0

### Description
The output from Visual Linter is "The path is not of a legal form". 

The file I have open is at `C:\Code\RC\BackOffice\Presentation\app\cache\expirationCache.js`

### Steps to recreate
1. Install Visual Linter
2. Open a JS file 
3. Look at the output for Visual Linter

### Current behavior
That error appears 

### Expected behavior
No error and the editor shows squiggly lines where there are errors

**Comment by woldner** [comment]
Sorry everyone; but the development of this extension has been suspended. 
You can read more about it here:
https://github.com/jwldnr/VisualLinter#deprecated
