### ISSUE TITLE
Special handling for typescript definitions

### ISSUE THREAD

**Issue by HolgerJeromin** [jwldnr/VisualLinter#62]
### Installed product versions
- Visual Studio: [example 2019 Professional]
- This extension: [example 1.1.104]

### Description
TypeScript Definitions are often auto generated or from third party, so I do not want linting hints for them.

### Steps to recreate
Just an example:
* Add rule for single quote.
* Open a TypeScript definition file `.d.ts` which was generated from my compiler. Every single quotes are converted to double quotes.

Many other rules are not valid for `.d.ts` files.
@typescript-eslint/explicit-member-accessibility as an example.

### Current behavior
When I open an `.d.ts` file I see many warning.

### Expected behavior
I see two Solutions here:
* VisualLinter should ignore all `.d.ts` files, 
* Or separate TypeScript and TypeScript Definitions in options: 
![image](https://user-images.githubusercontent.com/2410353/67942738-ce0d5a00-fbd8-11e9-8511-fe0af24ca2be.png)

**Comment by woldner** [comment]
Sorry everyone; but the development of this extension has been suspended. 
You can read more about it here:
https://github.com/jwldnr/VisualLinter#deprecated
