### ISSUE TITLE
red squigglies don't go away

### ISSUE THREAD

**Issue by mdodge-ecgrow** [jwldnr/VisualLinter#64]
### Installed product versions
- Visual Studio: [example 2015 Professional]
- This extension: [example 1.1.21]
Visual Studio Professional 2017
Visual Linter 1.1.0

### Description
Replace this text with a short description
In my App.js file, I removed a bunch of code to see if it would cause other code to error out due to 'no-unused-vars'.  It worked and added the red squigglies to those import statements.  Then I added the code back in and saved the file.  The red squigglies do not go away.  I've added some more code and saved.  Still there.
Update:  I have restarted Visual Studio and now they are gone.

### Steps to recreate
Create code and save code that has unused variables/imports.  View red squigglies correctly added.  Add in code that uses the imports and save the file.  View red squigglies do not go away.

### Current behavior
Red squigglies do not go away from error free code.

### Expected behavior
Red squigglies go away from error free code.

**Comment by woldner** [comment]
Sorry everyone; but the development of this extension has been suspended. 
You can read more about it here:
https://github.com/jwldnr/VisualLinter#deprecated
