### ISSUE TITLE
Broaden folders to search when looking for ESLint installation

### ISSUE THREAD

**Issue by jpreese** [jwldnr/VisualLinter#8]
I've been using this extension on a few projects lately, just trying to get it as much exposure as possible, and noticed the below.

### Installed product versions
- Visual Studio: 2017 Professional
- This extension: 1.0.120

### Description
Broaden directories to search in when trying to find a local eslint installation

### Steps to recreate
1. Put the node_modules directory above the solution directory
2. Run the linter using the local install option

### Current behavior
Extension only searches the solution directory and below. This causes a problem when the node_modules directory lives above the solution directory. An example of this would be a project that has a folder structure of:

```
project-root
├── node_modules
├── packages.json
└─┬ src
     ├── project.sln
     └── ...
```

### Expected behavior
Find the nearest local eslint installation, above or below the solution.

**Comment by jpreese** [comment]
FWIW it might be possible to simply run "npm root", get the output, and search from that point.

**Comment by jwldnr** [comment]
Thank you for the suggestion.
I've been looking into a better way to detect eslint config/installation recently but it did not land in anything.

I'll be looking into this further this week and see if I can decide on a better way.
I'll update this issue with my findings along the way.

**Comment by jwldnr** [comment]
This issue is addressed in #9 

If you're up to it you can get the latest beta build from [here](http://vsixgallery.com/extension/21d9f99b-ec42-4df4-8b16-2a62db5392a5/) and test before it is released on the Marketplace.

**Comment by jpreese** [comment]
Looks good to me 👍

**Comment by jwldnr** [comment]
Cool!

A new version `1.0.148` will soon be available on the Marketplace.
